services:
  bot-cache:
    container_name: redis-cache
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - auranetwork
  bot:
    container_name: aura-bot
    build: .
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      REDIS_HOST: ${REDIS_HOST:-bot-cache}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_TTL: ${REDIS_TTL:-3600}
      BOT_ID: ${BOT_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNERID: ${BOT_OWNERID}
      BOT_PRESENCE_TYPE: ${BOT_PRESENCE_TYPE:-0}
      BOT_PRESENCE_MSG: ${BOT_PRESENCE_MSG:-Discord}
      BOT_DEFAULT_LANGUAGE: ${BOT_DEFAULT_LANGUAGE:-en}
      JIKAN_API_URL: ${JIKAN_API_URL:-https://api.jikan.moe/v4}
    volumes:
      - ${LOGS_PATH:-./logs}:/app/logs
    networks:
      - auranetwork
    depends_on:
      - bot-cache

volumes:
  cache-data:

networks:
  auranetwork:
    driver: bridge
