services:
  cache:
    container_name: redis-cache
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--bind", "cache", "--port", "6379", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - auranetwork
  bot:
    container_name: aura-bot
    build: .
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_TTL: ${REDIS_TTL}
      BOT_ID: ${BOT_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNERID: ${BOT_OWNERID}
      BOT_PRESENCE_TYPE: ${BOT_PRESENCE_TYPE}
      BOT_PRESENCE_MSG: ${BOT_PRESENCE_MSG}
    volumes:
      - ${LOGS_PATH}:/app/logs
    networks:
      - auranetwork
    depends_on:
      - cache

volumes:
  cache:
    driver: local

networks:
  auranetwork:
    driver: bridge
