spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  application:
    name: aura.client
  redis:
    standalone:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

discord:
  bot-ownerId: ${BOT_OWNERID}
  bot-id: ${BOT_ID}
  bot-token: ${BOT_TOKEN}
  bot-presence-type: 3
  bot-presence-msg: Globo Rural

jikan:
  api-url: https://api.jikan.moe/v4