name: Main

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Install dependencies
        run: bash .cicd/install-dependencies.sh

      - name: Run build
        run: bash .cicd/build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Install dependencies
        run: bash .cicd/install-dependencies.sh

      - name: Run tests
        run: bash .cicd/tests.sh
